version: 2

sources:
    - name: SAP
      description: Files coming from SAP
      database: OQ_BRONZE
      schema: SAP
      tables:
        - name: SMALL_ROW_MATERIAL_MOD_PROC_STEP
          description: material row froom all the countries processed
    - name: OFF365
      description: Files coming from office 365 
      database: OQ_BRONZE
      schema: OFF365
      tables:
        - name: SOURCE_COUNTRY
          description: Look up Countries
          