
with FCT_MATERIALS as (
select
    NB_LINE 	,
    PRODUCT_CATEGORY 	,
    COMPONENT 	,
    MATERIAL_GROUP 	,
    RAW_MATERIAL 	,
    SUPPLIER_CODE 	,
    MATERIAL_CODE 	,
    REPLACE (SOURCE_COUNTRY,'Itally','Italy') AS SOURCE_COUNTRY, 	
    TRACEABILITY 	,
    ALIGNMENT_KERING_ST 	,
    PURCHASE_COUNTRY 	,
    RAW_HIDE_WET_BLUE_STAGE 	,
    WET_HIDE_WET_BLUE_STAGE 	,
    A_2023_INPUT_QUALITY 	,
    A_2023_INPUT_UNIT 	,
    CONVERSION_FACTOR 	,
    A_2023_QUANTITY_CONS_UNIT	,
    CONSOLIDATION_UNIT 	,
    SUPPLIER 	,
    CERTIFICATION 	,
    ADDITIONAL_QUESTION 	,
    ANSWER 	,
    TRADEMARK	,
    MODELLED_MATERIAL	,
    TIER	,
    PROCESS_STEP	

from {{ref("BRZ_RAW_MATERIAL_MODELLED_PROCESS_STEPS") }}
)

select
M.NB_LINE 	,
M.PRODUCT_CATEGORY 	,
M.COMPONENT 	,
M.MATERIAL_GROUP 	,
M.RAW_MATERIAL 	,
M.SUPPLIER_CODE 	,
M.MATERIAL_CODE 	,
REPLACE (M.SOURCE_COUNTRY,'Itally','Italy') AS SOURCE_COUNTRY, 	
M.TRACEABILITY 	,
M.ALIGNMENT_KERING_ST 	,
M.PURCHASE_COUNTRY 	,
M.RAW_HIDE_WET_BLUE_STAGE 	,
M.WET_HIDE_WET_BLUE_STAGE 	,
M.A_2023_INPUT_QUALITY 	,
M.A_2023_INPUT_UNIT 	,
M.CONVERSION_FACTOR 	,
M.A_2023_QUANTITY_CONS_UNIT	,
M.CONSOLIDATION_UNIT 	,
M.SUPPLIER 	,
M.CERTIFICATION 	,
M.ADDITIONAL_QUESTION 	,
M.ANSWER 	,
M.TRADEMARK	,
M.MODELLED_MATERIAL	,
M.TIER	,
M.PROCESS_STEP

FROM FCT_MATERIALS M


