version: 2

models:
  - name: BRZ_SMALL_ROW_MATERIAL_MOD_PROC_STEP
    description: Other model
    columns:
      - name: NB_LINE
        description: Primary key
        tests:
          - unique
          - not_null
  - name: SLV__MATERIAL_MODELLED_PROCESS_STEPS
    description: cleaned data
    columns:
      - name: NB_LINE
        description: Primary Key
        tests:
          - unique
          - not_null
